# Coding could be for important things? I did make variables for a logical question I would like to pose?
ungrouped:
  hosts:
    localhost:
webstats-for-powerplant:
  hosts:
    localhost:
    127.0.0.1:
dbservers:
  hosts:
    localhost:
    127.0.0.1:
    three.example.com:
nuclearplant-1:
  hosts:
    localhost:
    127.0.0.1:
reactorcore-1:
  hosts:
    localhost:
    127.0.0.1:
reactorcore-2:
  hosts:
    localhost:
    127.0.0.1:
nuclear-fusion-core:
  hosts:
    localhost:
    127.0.0.1:
