- hosts: localhost 
  tasks:
    
    - name: Update and upgrade DNF package(S) on RHET system
      become: true
      dnf:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 5069 

    - name: Install Rkhunter on Ubuntu
      become: true
      dnf:
        name: rkhunter

    - name: Install Tripwire on Ubuntu 
      become: true
      dnf:
        name: tripwire

    - name: Install Fail2ban on Ubuntu 
      become: true
      dnf:
        name: fail2ban 

    - name: Install Crowdsec on Ubuntu 
      become: true
      dnf:
        name: crowdsec

    - name: Run a command for Crowdsec Status Check
      ansible.builtin.raw: systemctl status crowdsec
      args:
        executable: /bin/bash

    - name: Run a command for Fail2Ban Status Check
      ansible.builtin.raw: systemctl status fail2ban
      args:
        executable: /bin/bash
