#
# Playbook for Updating Security
# Rocky/Fedora/CentOS/Alma script next -- notes for self: update this, as reconfiguring next machine. 
#
---
- hosts: localhost
  tasks:
   - name: Update and upgrade apt-get / apt packages on Ubuntu system
     become: true
     dnf:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 5069 

   - name: Install Rkhunter
     become: true
     dnf:
       name: rkhunter

   - name: Install tripwire
     become: true
     dnf:
       name: tripwire

   - name: Install fail2ban
     become: true
     dnf:
       name: fail2ban

   - name: Install UsbGuard
     become: true
     dnf:
       name: usbguard

   - name: Install Crowdsec
     become: true
     dnf:
       name: crowdsec

   - name: Crowdsec Status Check
     service:
       name: crowdsec
       state: started
       enabled: yes 

   - name: Fail2Ban Status Check
     service:
       name: fail2ban
       state: started
       enabled: yes 

   - name: Run a command for Rkhunter to Update
     ansible.builtin.raw: rkhunter --update
     args:
       executable: /bin/bash

   - name: Run a command for Rkhunter to PropUpdt
     ansible.builtin.raw: rkhunter --propupd
     args:
       executable: /bin/bash

   - name: Run a command for Rkhunter to Check Sys Files
     ansible.builtin.raw: rkhunter --check
     args:
       executable: /bin/bash

   - name: Run a command for Tripwire to Check
     ansible.builtin.raw: tripwire --check
     args:
       executable: /bin/bash

   - name: USB Guard Show Devices 
     ansible.builtin.raw: usbguard list-devices #sring here to accept all 
     args:
       executable: /bin/bash

